### ISSUE TITLE
Cannot compile on MacBook Pro (M1)

### ISSUE THREAD

**Issue by cathleen-sl** [Sambruk/EgilSCIM#160]
We were hoping to test our implementation of an EGIL scim server but are unable to compile the client:

```
$ make
Consolidate compiler generated dependencies of target Egil
[  2%] Building CXX object CMakeFiles/Egil.dir/src/config_file.cpp.o
In file included from /Users/cat/dev/scimPlayground/EgilSCIM/src/config_file.cpp:20:
/Users/cat/dev/scimPlayground/EgilSCIM/src/config_file.hpp:61:16: warning: returning address of local temporary object [-Wreturn-stack-address]
        return filename.u8string().c_str();
               ^~~~~~~~~~~~~~~~~~~
/Users/cat/dev/scimPlayground/EgilSCIM/src/config_file.cpp:55:32: error: no matching function for call to 'canonical'
    std::string content = read(filesystem::canonical(file, filename.parent_path()));
                               ^~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:1859:39: note: candidate function not viable: no known conversion from 'std::filesystem::path' to 'std::error_code &' for 2nd argument
inline _LIBCPP_INLINE_VISIBILITY path canonical(const path& __p,
                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:1855:39: note: candidate function not viable: requires single argument '__p', but 2 arguments were provided
inline _LIBCPP_INLINE_VISIBILITY path canonical(const path& __p) {
                                      ^
/Users/cat/dev/scimPlayground/EgilSCIM/src/config_file.cpp:237:12: error: no matching function for call to 'absolute'
    return filesystem::absolute(path, filename.parent_path()).u8string();
           ^~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:1850:39: note: candidate function not viable: no known conversion from 'std::filesystem::path' to 'std::error_code &' for 2nd argument
inline _LIBCPP_INLINE_VISIBILITY path absolute(const path& __p,
                                      ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX12.3.sdk/usr/include/c++/v1/filesystem:1846:39: note: candidate function not viable: requires single argument '__p', but 2 arguments were provided
inline _LIBCPP_INLINE_VISIBILITY path absolute(const path& __p) {
                                      ^
1 warning and 2 errors generated.
make[3]: *** [CMakeFiles/Egil.dir/src/config_file.cpp.o] Error 1
make[2]: *** [CMakeFiles/Egil.dir/all] Error 2
make[1]: *** [CMakeFiles/EgilSCIMClient.dir/rule] Error 2
make: *** [EgilSCIMClient] Error 2
```
Any hints on what to do here? 

On a side note it would be great if this client could be made available through a Docker image so that we could bypass building it ourselves altogether.

**Comment by joesiltberg** [comment]
Building on MacOS hasn't been actively maintained unfortunately. 

It looks like the errors you're seeing stem from the fact that we're using the experimental filesystem library (since std::filesystem wasn't generally available at the time), and your compiler seems to use the std::filesystem functions. Unfortunately a couple of functions don't work the same way in std::filesystem as they did in experimental.

So if you want to build it on MacOS I think you will need to either figure out how to enable the experimental filesystem library, or rewrite the code a bit in a few places so it uses the std::filesystem functions instead.

I can't really advice on the first option, but a quick google shows:

https://stackoverflow.com/questions/42633477/macos-clang-c17-filesystem-header-not-found

I guess it depends on which compiler and version you have installed, possibly you need a linker flag such as `-lc++experimental` as mentioned above.

I created an issue for removing dependencies on experimental/filesystem ( https://github.com/Sambruk/EgilSCIM/issues/161 ), but I'm not sure when I can find time to work on that.

**Comment by cathleen-sl** [comment]
i will have a look and see what i can do (c++ novice here), thanks for getting back to me!

any thoughts on providing the client via docker image?

**Comment by joesiltberg** [comment]
You could possibly use the EgilAdmin image already, it's on DockerHub as sambruk/egiladmin :

https://hub.docker.com/r/sambruk/egiladmin

This is a packaged version including a web based administration interface. It requires a license key to use properly (but can be evaluated freely), but if the company you're working on is a member of Sambruk's EGIL group you could probably get a license key.

But if you want to run it from the command line, the EgilSCIMClient binary is installed in that docker image.
